# Generated by Django 4.0.4 on 2022-05-04 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_entrada',
            name='estacionamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamiento.area'),
        ),
    ]
