# Generated by Django 4.0.4 on 2022-05-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_registro_entrada_estacionamiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_entrada',
            old_name='estado_salida',
            new_name='estado_de_salida',
        ),
    ]
