# Generated by Django 4.0.4 on 2022-05-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_rename_estado_salida_registro_entrada_estado_de_salida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_pago',
            name='monto_pagado',
        ),
    ]
